### ISSUE TITLE
phpbb 3.1.10 migration error

### ISSUE THREAD

**Issue by Scanialady** [bb3mobi/medals#3]
I tried to install on a fresh phpBB 3.1.10 (your medals github version from 2016-11-21).
I got the following SQL error:

`
SQL ERROR [ mysqli ]

Duplicate entry '\bb3mobi\medals\migrations\v_1_0_1' for key 'PRIMARY' [1062]

SQL

INSERT INTO phpbb_migrations (migration_depends_on, migration_schema_done, migration_data_done, migration_data_state, migration_start_time, migration_end_time, migration_name) VALUES ('a:1:{i:0;s:34:\"\\bb3mobi\\medals\\migrations\\v_1_0_0\";}', 0, 0, '', 1480622511, 0, '\\bb3mobi\\medals\\migrations\\v_1_0_1')

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 855
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 729
CALL: phpbb\db\driver\factory->sql_query()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 310
CALL: phpbb\db\migrator->set_migration_state()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 216
CALL: phpbb\db\migrator->try_apply()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 199
CALL: phpbb\db\migrator->update_do()

FILE: [ROOT]/phpbb/extension/base.php
LINE: 80
CALL: phpbb\db\migrator->update()

FILE: [ROOT]/phpbb/extension/manager.php
LINE: 187
CALL: phpbb\extension\base->enable_step()

FILE: [ROOT]/includes/acp/acp_extensions.php
LINE: 177
CALL: phpbb\extension\manager->enable_step()

FILE: [ROOT]/includes/functions_module.php
LINE: 674
CALL: acp_extensions->main()

FILE: [ROOT]/adm/index.php
LINE: 81
CALL: p_master->load_active()
`

**Comment by bb3mobi** [comment]
Try to download now.

**Comment by Scanialady** [comment]
Installation on fresh 3.1.10 works now.
re-activation on 3.2.0 (upgraded from 3.1.9) does work, too.
Thank you :)
